### PR TITLE
Complete overhaul of the original library

### PR DESCRIPTION
**Pull request by KeeperB5**
The important changes are listed in the following commit: 
https://github.com/KeeperB5/Bia.Countries/commit/789d63a2b680234755176b5cc529a62005e16c12

Readme.md has also been updated, see https://github.com/KeeperB5/Bia.Countries for live version of it.

If this pull request is accepted, "Install / Download" part of the Readme.md needs to be updated again. I would be willing to maintain package at PowerShell Gallery. I would also like to keep providing a standalone zip-download who just want to grab the single dll quickly.

Since this is a complete overhaul of the library and nothing like the original, I understand if this pull request is not accepted. But if the pull request is accepted, might I suggest a major version bump to v2.0.

Thanks for your time!

### CODE REVIEW

**Comment by ilyabreev** [comment]
The only unacceptable thing is ReadOnlyCollection. One of the purposes of library is to provide really fast lookup of ISO-3166 information by country name. ReadOnlyCollection means iteration through the whole list of countries in the worst case.

**Comment by KeeperB5** [comment]
Yes it does. But there are so many other properties people will want to look up countries by, such as alpha2 and numeric. And in my case, Active Directory name. If you benchmark the Linq queries, you'll find they are really fast nevertheless. The collection is not so large as to really have noticeable lag in queries.

**Comment by ilyabreev** [comment]
Performance looks not as bad as I thought.
What about case sensitivity in search?

**Comment by KeeperB5** [comment]
GetCountryByPartialShortName, GetCountryByPartialFullName and GetCountryByPartialActiveDirectoryName handle case-insensitive (partial) match lookups.

**Comment by KeeperB5** [comment]
Let me know if you would prefer me to handle the PowerShell Gallery package? Thanks.

**Comment by ilyabreev** [comment]
Yeah, it would be great.

**Comment by KeeperB5** [comment]
I was wondering if there is a problem, or if you simply have been busy?

**Comment by ilyabreev** [comment]
Sorry, just been busy.
Solution build is failing now.
The root cause is 

`Warning	104	Could not resolve this reference. Could not locate the assembly "HtmlAgilityPack, Version=1.4.9.5, Culture=neutral, PublicKeyToken=bd319b19eaf3b43a, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	Bia.Countries.Parser
Warning	103	Could not resolve this reference. Could not locate the assembly "nunit.framework, Version=3.5.0.0, Culture=neutral, PublicKeyToken=2638cd05610744eb, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.	Bia.Countries.Tests
`

**Comment by ilyabreev** [comment]
Fixed this by reinstalling HtmlAgilityPack package.

**Comment by ilyabreev** [comment]
Submit is done. 
Package is indexing. https://www.nuget.org/packages/Bia.Countries/2.0.0

**Pull request merged**
